#!/usr/bin/env python3
"""Add public-domain literature docs. Run from repo root:
   .venv/bin/python3 tools/batch_lists/literature.py
"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.batch_add import add_many

DOCS = [
    # ===== POEMS (short, one per file) =====
    # Emily Dickinson
    {"url": "https://en.wikisource.org/wiki/Because_I_could_not_stop_for_Death",
     "slug": "dickinson-because-i-could-not-stop-for-death",
     "title": "Because I could not stop for Death", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Emily Dickinson", "license": "public-domain",
     "tags": ["american-poetry", "19th-century", "death"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Hope_is_the_thing_with_feathers",
     "slug": "dickinson-hope-is-the-thing-with-feathers",
     "title": "Hope is the thing with feathers", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Emily Dickinson", "license": "public-domain",
     "tags": ["american-poetry", "19th-century"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/I%27m_Nobody!_Who_are_you%3F",
     "slug": "dickinson-im-nobody-who-are-you",
     "title": "I'm Nobody! Who are you?", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Emily Dickinson", "license": "public-domain",
     "tags": ["american-poetry", "19th-century", "identity"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Walt Whitman
    {"url": "https://en.wikisource.org/wiki/Leaves_of_Grass_(1891%E2%80%9392)/O_Captain!_My_Captain!",
     "slug": "whitman-o-captain-my-captain",
     "title": "O Captain! My Captain!", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Walt Whitman", "license": "public-domain",
     "tags": ["american-poetry", "19th-century", "elegy"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Robert Frost
    {"url": "https://en.wikisource.org/wiki/The_Road_Not_Taken",
     "slug": "frost-the-road-not-taken",
     "title": "The Road Not Taken", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Robert Frost", "license": "public-domain",
     "tags": ["american-poetry", "modernist", "nature"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1900-1950", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Stopping_by_Woods_on_a_Snowy_Evening",
     "slug": "frost-stopping-by-woods",
     "title": "Stopping by Woods on a Snowy Evening", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Robert Frost", "license": "public-domain",
     "tags": ["american-poetry", "modernist", "winter"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1900-1950", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Shakespeare sonnets
    {"url": "https://en.wikisource.org/wiki/Shakespeare%27s_Sonnets_(1923)_Yale/18",
     "slug": "shakespeare-sonnet-18",
     "title": "Sonnet 18 (Shall I compare thee to a summer's day)",
     "content_type": "sonnet", "domain": "literature", "source_name": "wikisource",
     "author": "William Shakespeare", "license": "public-domain",
     "tags": ["english-poetry", "renaissance", "love", "sonnet"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Shakespeare%27s_Sonnets_(1923)_Yale/130",
     "slug": "shakespeare-sonnet-130",
     "title": "Sonnet 130 (My mistress' eyes are nothing like the sun)",
     "content_type": "sonnet", "domain": "literature", "source_name": "wikisource",
     "author": "William Shakespeare", "license": "public-domain",
     "tags": ["english-poetry", "renaissance", "sonnet"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Longfellow, Wordsworth, Keats, Tennyson
    {"url": "https://en.wikisource.org/wiki/Paul_Revere%27s_Ride",
     "slug": "longfellow-paul-reveres-ride",
     "title": "Paul Revere's Ride", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Henry Wadsworth Longfellow", "license": "public-domain",
     "tags": ["american-poetry", "19th-century", "history", "narrative-verse"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "third-person", "structure": "verse",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/I_Wandered_Lonely_as_a_Cloud",
     "slug": "wordsworth-i-wandered-lonely-as-a-cloud",
     "title": "I Wandered Lonely as a Cloud", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "William Wordsworth", "license": "public-domain",
     "tags": ["english-poetry", "romantic", "nature"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Ode_on_a_Grecian_Urn",
     "slug": "keats-ode-on-a-grecian-urn",
     "title": "Ode on a Grecian Urn", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "John Keats", "license": "public-domain",
     "tags": ["english-poetry", "romantic", "aesthetics"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Dunbar, Johnson (Black American poets, public domain)
    {"url": "https://en.wikisource.org/wiki/We_Wear_the_Mask",
     "slug": "dunbar-we-wear-the-mask",
     "title": "We Wear the Mask", "content_type": "poem",
     "domain": "literature", "source_name": "wikisource",
     "author": "Paul Laurence Dunbar", "license": "public-domain",
     "tags": ["american-poetry", "19th-century", "identity"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Wheatley
    {"url": "https://en.wikisource.org/wiki/Poems_on_Various_Subjects,_Religious_and_Moral/On_Being_Brought_from_Africa_to_America",
     "slug": "wheatley-on-being-brought-from-africa",
     "title": "On Being Brought from Africa to America",
     "content_type": "poem", "domain": "literature", "source_name": "wikisource",
     "author": "Phillis Wheatley", "license": "public-domain",
     "tags": ["american-poetry", "18th-century", "religion"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # ===== SHORT STORIES (full text) =====
    {"url": "https://en.wikisource.org/wiki/The_Gift_of_the_Magi",
     "slug": "o-henry-gift-of-the-magi",
     "title": "The Gift of the Magi", "content_type": "short-story",
     "domain": "literature", "source_name": "wikisource",
     "author": "O. Henry", "license": "public-domain",
     "tags": ["american-fiction", "christmas", "short-fiction"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1900-1950", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/The_Yellow_Wall-Paper_(Gilman,_1899)",
     "slug": "gilman-yellow-wallpaper",
     "title": "The Yellow Wallpaper", "content_type": "short-story",
     "domain": "literature", "source_name": "wikisource",
     "author": "Charlotte Perkins Gilman", "license": "public-domain",
     "tags": ["american-fiction", "feminism", "19th-century"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/A_Vision_of_the_Last_Judgment_(Blake)",
     "slug": "blake-vision-last-judgment",
     "title": "A Vision of the Last Judgment", "content_type": "essay",
     "domain": "literature", "source_name": "wikisource",
     "author": "William Blake", "license": "public-domain",
     "tags": ["english-literature", "mysticism", "art-criticism"],
     "tone": "poetic", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "analyze", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # ===== NOVEL EXCERPTS / CHAPTERS (fetch whole, excerpt with edit later if huge) =====
    # Jane Eyre chapter 1
    {"url": "https://en.wikisource.org/wiki/Jane_Eyre/Volume_1/Chapter_1",
     "slug": "bronte-jane-eyre-ch1",
     "title": "Jane Eyre — Chapter 1", "content_type": "novel-excerpt",
     "domain": "literature", "source_name": "wikisource",
     "author": "Charlotte Brontë", "license": "public-domain",
     "tags": ["english-novel", "19th-century", "first-person-narrator"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1 only"},
    # Great Gatsby (1925, now public domain)
    {"url": "https://en.wikisource.org/wiki/The_Great_Gatsby/Chapter_1",
     "slug": "fitzgerald-great-gatsby-ch1",
     "title": "The Great Gatsby — Chapter 1", "content_type": "novel-excerpt",
     "domain": "literature", "source_name": "wikisource",
     "author": "F. Scott Fitzgerald", "license": "public-domain",
     "tags": ["american-novel", "jazz-age", "modernist"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1900-1950", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1"},
    # Wuthering Heights chapter 1
    {"url": "https://en.wikisource.org/wiki/Wuthering_Heights/Chapter_I",
     "slug": "bronte-wuthering-heights-ch1",
     "title": "Wuthering Heights — Chapter 1", "content_type": "novel-excerpt",
     "domain": "literature", "source_name": "wikisource",
     "author": "Emily Brontë", "license": "public-domain",
     "tags": ["english-novel", "19th-century", "gothic"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1"},
    # Alice in Wonderland chapter 1
    {"url": "https://en.wikisource.org/wiki/Alice%27s_Adventures_in_Wonderland_(1866)/Chapter_1",
     "slug": "carroll-alice-ch1",
     "title": "Alice's Adventures in Wonderland — Chapter 1",
     "content_type": "novel-excerpt", "domain": "literature",
     "source_name": "wikisource", "author": "Lewis Carroll",
     "license": "public-domain",
     "tags": ["children-literature", "victorian", "fantasy"],
     "tone": "narrative", "register": "literary", "audience": "children",
     "era": "1800-1900", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1 only"},
    # Don Quixote opening
    {"url": "https://en.wikisource.org/wiki/Don_Quixote_(Ormsby)/Volume_1/Part_1/Chapter_1",
     "slug": "cervantes-don-quixote-ch1",
     "title": "Don Quixote — Part 1 Chapter 1 (Ormsby translation)",
     "content_type": "novel-excerpt", "domain": "literature",
     "source_name": "wikisource", "author": "Miguel de Cervantes",
     "license": "public-domain",
     "tags": ["spanish-novel", "translation", "picaresque"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1; Ormsby translation"},
    # Huck Finn chapter 1
    {"url": "https://en.wikisource.org/wiki/Adventures_of_Huckleberry_Finn/Chapter_1",
     "slug": "twain-huck-finn-ch1",
     "title": "Adventures of Huckleberry Finn — Chapter 1",
     "content_type": "novel-excerpt", "domain": "literature",
     "source_name": "wikisource", "author": "Mark Twain",
     "license": "public-domain",
     "tags": ["american-novel", "19th-century", "vernacular-prose"],
     "tone": "narrative", "register": "colloquial", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True},

    # ===== FABLES & FOLK TALES =====
    {"url": "https://en.wikisource.org/wiki/Aesop%27s_Fables_(V._S._Vernon_Jones)/The_Fox_and_the_Grapes",
     "slug": "aesop-fox-and-grapes",
     "title": "The Fox and the Grapes (Aesop)", "content_type": "fable",
     "domain": "literature", "source_name": "wikisource",
     "author": "Aesop", "license": "public-domain",
     "tags": ["fable", "classical", "moral"],
     "tone": "narrative", "register": "plain", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Aesop%27s_Fables_(V._S._Vernon_Jones)/The_Tortoise_and_the_Hare",
     "slug": "aesop-tortoise-and-hare",
     "title": "The Tortoise and the Hare (Aesop)", "content_type": "fable",
     "domain": "literature", "source_name": "wikisource",
     "author": "Aesop", "license": "public-domain",
     "tags": ["fable", "classical", "moral"],
     "tone": "narrative", "register": "plain", "audience": "children",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Household_Stories_(Grimm,_Crane_and_Edwardes)/Rumpelstiltskin",
     "slug": "grimm-rumpelstiltskin",
     "title": "Rumpelstiltskin (Grimm)", "content_type": "children-story",
     "domain": "literature", "source_name": "wikisource",
     "author": "Brothers Grimm", "license": "public-domain",
     "tags": ["fairy-tale", "german-folklore", "grimm"],
     "tone": "narrative", "register": "plain", "audience": "children",
     "era": "1800-1900", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Household_Stories_(Grimm,_Crane_and_Edwardes)/Hansel_and_Grethel",
     "slug": "grimm-hansel-and-gretel",
     "title": "Hansel and Gretel (Grimm)", "content_type": "children-story",
     "domain": "literature", "source_name": "wikisource",
     "author": "Brothers Grimm", "license": "public-domain",
     "tags": ["fairy-tale", "german-folklore", "grimm"],
     "tone": "narrative", "register": "plain", "audience": "children",
     "era": "1800-1900", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/The_Arabian_Nights_Entertainments/The_History_of_Ali_Baba_and_the_Forty_Robbers",
     "slug": "arabian-nights-ali-baba",
     "title": "Ali Baba and the Forty Robbers", "content_type": "short-story",
     "domain": "literature", "source_name": "wikisource",
     "author": "Anonymous (Arabian Nights)", "license": "public-domain",
     "tags": ["arabic-folklore", "arabian-nights", "adventure"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "anonymous",
     "excerpted": True},

    # ===== ESSAYS =====
    # Emerson
    {"url": "https://en.wikisource.org/wiki/Self-Reliance",
     "slug": "emerson-self-reliance",
     "title": "Self-Reliance", "content_type": "essay",
     "domain": "philosophy", "source_name": "wikisource",
     "author": "Ralph Waldo Emerson", "license": "public-domain",
     "tags": ["transcendentalism", "american-essay", "individualism"],
     "tone": "argumentative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Montaigne (translated)
    {"url": "https://en.wikisource.org/wiki/Essays_of_Montaigne/Book_I/Chapter_XX",
     "slug": "montaigne-that-to-philosophize-is-to-learn-to-die",
     "title": "That to Philosophize Is to Learn to Die (Montaigne)",
     "content_type": "essay", "domain": "philosophy",
     "source_name": "wikisource", "author": "Michel de Montaigne",
     "license": "public-domain",
     "tags": ["french-essay", "philosophy", "renaissance"],
     "tone": "argumentative", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "analyze", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    # Thoreau
    {"url": "https://en.wikisource.org/wiki/Walden/Chapter_I",
     "slug": "thoreau-walden-economy-excerpt",
     "title": "Walden — Economy (Chapter 1, excerpt)",
     "content_type": "essay", "domain": "philosophy",
     "source_name": "wikisource", "author": "Henry David Thoreau",
     "license": "public-domain",
     "tags": ["american-essay", "transcendentalism", "nature"],
     "tone": "argumentative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "First chapter (Economy) — excerpt of longer chapter"},
    # Mary Wollstonecraft
    {"url": "https://en.wikisource.org/wiki/A_Vindication_of_the_Rights_of_Woman/Chapter_I",
     "slug": "wollstonecraft-rights-of-woman-ch1",
     "title": "A Vindication of the Rights of Woman — Chapter 1",
     "content_type": "essay", "domain": "philosophy",
     "source_name": "wikisource", "author": "Mary Wollstonecraft",
     "license": "public-domain",
     "tags": ["feminist-philosophy", "18th-century", "rights"],
     "tone": "argumentative", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1 only"},

    # ===== HAIKU =====
    {"url": "https://en.wikisource.org/wiki/Translations:Basho%27s_frog",
     "slug": "basho-old-pond-haiku",
     "title": "Basho — Old Pond (haiku, multiple translations)",
     "content_type": "haiku", "domain": "literature",
     "source_name": "wikisource", "author": "Matsuo Basho",
     "license": "public-domain", "language": "en",
     "tags": ["japanese-poetry", "haiku", "zen", "translation"],
     "tone": "poetic", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "verse",
     "purpose": "creative-expression", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Original pre-1800; English translations"},

    # ===== LETTERS =====
    # Famous Thomas Jefferson letter
    {"url": "https://en.wikisource.org/wiki/Letter_to_Peter_Carr,_with_Enclosure_(10_August_1787)",
     "slug": "jefferson-letter-peter-carr-1787",
     "title": "Letter to Peter Carr (Jefferson, 1787)",
     "content_type": "letter", "domain": "history",
     "source_name": "wikisource", "author": "Thomas Jefferson",
     "license": "public-domain",
     "tags": ["founding-fathers", "18th-century", "education", "private-letter"],
     "tone": "formal", "register": "literary", "audience": "niche-enthusiast",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "inform", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # ===== DIARIES =====
    {"url": "https://en.wikisource.org/wiki/Diary_of_Samuel_Pepys/1660/January",
     "slug": "pepys-diary-jan-1660",
     "title": "Diary of Samuel Pepys — January 1660",
     "content_type": "diary-entry", "domain": "history",
     "source_name": "wikisource", "author": "Samuel Pepys",
     "license": "public-domain",
     "tags": ["17th-century", "english-diary", "london"],
     "tone": "informal", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "document", "expertise_required": "generalist",
     "quality_disposition": "professional", "authorship": "human-written",
     "excerpted": True, "notes": "January 1660 entries"},

    # ===== TRAVELOGUE =====
    {"url": "https://en.wikisource.org/wiki/The_Innocents_Abroad/Chapter_I",
     "slug": "twain-innocents-abroad-ch1",
     "title": "The Innocents Abroad — Chapter 1",
     "content_type": "travelogue", "domain": "travel",
     "source_name": "wikisource", "author": "Mark Twain",
     "license": "public-domain",
     "tags": ["american-literature", "19th-century-travel", "humor"],
     "tone": "satirical", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Chapter 1"},

    # ===== PHILOSOPHY / RELIGION =====
    {"url": "https://en.wikisource.org/wiki/Tao_Te_Ching_(Legge)/Book_1",
     "slug": "laozi-tao-te-ching-book-1-legge",
     "title": "Tao Te Ching — Book 1 (Legge translation)",
     "content_type": "religious-text-excerpt", "domain": "religion",
     "source_name": "wikisource", "author": "Laozi (attrib.)",
     "license": "public-domain",
     "tags": ["taoism", "chinese-philosophy", "translation"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "verse",
     "purpose": "inform", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Book 1 only"},
    {"url": "https://en.wikisource.org/wiki/Analects_(Legge)/Book_I",
     "slug": "confucius-analects-book-1-legge",
     "title": "Analects — Book 1 (Legge translation)",
     "content_type": "philosophy-text", "domain": "philosophy",
     "source_name": "wikisource", "author": "Confucius",
     "license": "public-domain",
     "tags": ["confucianism", "chinese-philosophy", "classical", "translation"],
     "tone": "reverent", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "inform", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Book I only"},
    {"url": "https://en.wikisource.org/wiki/Bible_(King_James)/Ecclesiastes",
     "slug": "kjv-ecclesiastes",
     "title": "Ecclesiastes (King James Version)",
     "content_type": "religious-text-excerpt", "domain": "religion",
     "source_name": "wikisource", "author": "Anonymous (traditionally Solomon)",
     "license": "public-domain",
     "tags": ["bible", "old-testament", "wisdom-literature", "kjv"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "verse",
     "purpose": "inform", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "anonymous"},

    # ===== TRANSLATIONS of ancient works =====
    {"url": "https://en.wikisource.org/wiki/The_Iliad_(Pope)/Book_1",
     "slug": "homer-iliad-book-1-pope",
     "title": "The Iliad — Book 1 (Pope translation)",
     "content_type": "poem", "domain": "literature",
     "source_name": "wikisource", "author": "Homer",
     "license": "public-domain",
     "tags": ["greek-epic", "classical", "translation", "epic-verse"],
     "tone": "narrative", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "verse",
     "purpose": "entertain", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Book 1; Pope translation"},
]

if __name__ == "__main__":
    add_many(DOCS)
