#!/usr/bin/env python3
"""Historical documents and speeches batch."""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.batch_add import add_many

DOCS = [
    # Founding documents
    {"url": "https://en.wikisource.org/wiki/Declaration_of_Independence_(1776)",
     "slug": "us-declaration-of-independence",
     "title": "US Declaration of Independence (1776)",
     "content_type": "historical-document", "domain": "politics",
     "source_name": "wikisource",
     "author": "Second Continental Congress (Thomas Jefferson principal drafter)",
     "license": "public-domain",
     "tags": ["founding-documents", "18th-century", "american-history"],
     "tone": "formal", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "committee-drafted"},
    {"url": "https://en.wikisource.org/wiki/Constitution_of_the_United_States_of_America",
     "slug": "us-constitution",
     "title": "Constitution of the United States (1787)",
     "content_type": "historical-document", "domain": "law",
     "source_name": "wikisource", "author": "Constitutional Convention",
     "license": "public-domain",
     "tags": ["founding-documents", "18th-century", "constitutional-law"],
     "tone": "formal", "register": "bureaucratic", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person",
     "structure": "hierarchical-sections", "purpose": "legally-bind",
     "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "committee-drafted"},
    {"url": "https://en.wikisource.org/wiki/Bill_of_Rights",
     "slug": "us-bill-of-rights",
     "title": "US Bill of Rights (1791)",
     "content_type": "historical-document", "domain": "law",
     "source_name": "wikisource", "author": "US Congress",
     "license": "public-domain",
     "tags": ["founding-documents", "amendments", "rights"],
     "tone": "formal", "register": "bureaucratic", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person",
     "structure": "hierarchical-sections", "purpose": "legally-bind",
     "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "committee-drafted"},
    {"url": "https://en.wikisource.org/wiki/Magna_Carta",
     "slug": "magna-carta",
     "title": "Magna Carta (1215)", "content_type": "historical-document",
     "domain": "law", "source_name": "wikisource",
     "author": "King John and English barons", "license": "public-domain",
     "tags": ["medieval", "english-law", "constitutional-history"],
     "tone": "formal", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person",
     "structure": "hierarchical-sections", "purpose": "legally-bind",
     "expertise_required": "expert",
     "quality_disposition": "exemplary", "authorship": "committee-drafted",
     "excerpted": True},

    # Common Sense / Paine
    {"url": "https://en.wikisource.org/wiki/Common_Sense",
     "slug": "paine-common-sense-excerpt",
     "title": "Common Sense (Paine, 1776) — excerpt",
     "content_type": "essay", "domain": "politics",
     "source_name": "wikisource", "author": "Thomas Paine",
     "license": "public-domain",
     "tags": ["revolutionary-pamphlet", "18th-century", "american-history"],
     "tone": "persuasive", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "First section only"},

    # Other major historical documents
    {"url": "https://en.wikisource.org/wiki/Emancipation_Proclamation",
     "slug": "lincoln-emancipation-proclamation",
     "title": "Emancipation Proclamation (1863)",
     "content_type": "historical-document", "domain": "politics",
     "source_name": "wikisource", "author": "Abraham Lincoln",
     "license": "public-domain",
     "tags": ["19th-century", "american-civil-war", "executive-order"],
     "tone": "formal", "register": "bureaucratic", "audience": "general",
     "era": "1800-1900", "perspective": "third-person", "structure": "prose",
     "purpose": "legally-bind", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "institutional"},
    {"url": "https://en.wikisource.org/wiki/Universal_Declaration_of_Human_Rights",
     "slug": "universal-declaration-human-rights-1948",
     "title": "Universal Declaration of Human Rights (1948)",
     "content_type": "historical-document", "domain": "law",
     "source_name": "wikisource", "author": "United Nations General Assembly",
     "license": "public-domain",
     "tags": ["international-law", "human-rights", "postwar"],
     "tone": "formal", "register": "bureaucratic", "audience": "general",
     "era": "1900-1950", "perspective": "third-person",
     "structure": "hierarchical-sections", "purpose": "document",
     "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "committee-drafted"},

    # Speeches
    {"url": "https://en.wikisource.org/wiki/Address_at_Cooper_Institute",
     "slug": "lincoln-cooper-union-address",
     "title": "Lincoln Cooper Union Address (1860)",
     "content_type": "speech", "domain": "politics",
     "source_name": "wikisource", "author": "Abraham Lincoln",
     "license": "public-domain",
     "tags": ["19th-century", "political-speech", "american-history"],
     "tone": "argumentative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Excerpted"},
    {"url": "https://en.wikisource.org/wiki/Second_Inaugural_Address_of_Abraham_Lincoln",
     "slug": "lincoln-second-inaugural",
     "title": "Second Inaugural Address (Lincoln, 1865)",
     "content_type": "inaugural-address", "domain": "politics",
     "source_name": "wikisource", "author": "Abraham Lincoln",
     "license": "public-domain",
     "tags": ["19th-century", "inaugural", "american-civil-war"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/First_inaugural_address_of_Franklin_D._Roosevelt",
     "slug": "fdr-first-inaugural",
     "title": "First Inaugural Address (FDR, 1933)",
     "content_type": "inaugural-address", "domain": "politics",
     "source_name": "wikisource", "author": "Franklin D. Roosevelt",
     "license": "public-domain",
     "tags": ["20th-century", "inaugural", "great-depression"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "1900-1950", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Inaugural_Address_of_John_F._Kennedy",
     "slug": "jfk-inaugural-address",
     "title": "Inaugural Address (JFK, 1961)",
     "content_type": "inaugural-address", "domain": "politics",
     "source_name": "wikisource", "author": "John F. Kennedy",
     "license": "public-domain",
     "tags": ["20th-century", "inaugural", "cold-war"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "1950-2000", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Atlanta_Compromise_Speech",
     "slug": "booker-t-washington-atlanta-compromise",
     "title": "Atlanta Compromise Speech (Booker T. Washington, 1895)",
     "content_type": "speech", "domain": "politics",
     "source_name": "wikisource", "author": "Booker T. Washington",
     "license": "public-domain",
     "tags": ["19th-century", "american-politics"],
     "tone": "argumentative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Women%27s_Rights_Convention_at_Seneca_Falls",
     "slug": "seneca-falls-declaration-of-sentiments",
     "title": "Declaration of Sentiments (Seneca Falls, 1848)",
     "content_type": "historical-document", "domain": "politics",
     "source_name": "wikisource",
     "author": "Elizabeth Cady Stanton et al.", "license": "public-domain",
     "tags": ["19th-century", "women-suffrage", "american-history"],
     "tone": "argumentative", "register": "literary", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "committee-drafted"},

    # Ancient speeches (translations)
    {"url": "https://en.wikisource.org/wiki/Pericles%27s_Funeral_Oration_(Crawley)",
     "slug": "pericles-funeral-oration-crawley",
     "title": "Pericles' Funeral Oration (Crawley translation)",
     "content_type": "speech", "domain": "history",
     "source_name": "wikisource", "author": "Pericles (recorded by Thucydides)",
     "license": "public-domain",
     "tags": ["ancient-greek", "classical", "translation"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},
    {"url": "https://en.wikisource.org/wiki/Edicts_of_Ashoka",
     "slug": "edicts-of-ashoka",
     "title": "Edicts of Ashoka",
     "content_type": "historical-document", "domain": "history",
     "source_name": "wikisource", "author": "Emperor Ashoka",
     "license": "public-domain",
     "tags": ["ancient-india", "buddhism", "imperial-edicts", "translation"],
     "tone": "reverent", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "document", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "institutional",
     "excerpted": True, "notes": "Selected edicts"},

    # US government founding-ish
    {"url": "https://en.wikisource.org/wiki/George_Washington%27s_Farewell_Address",
     "slug": "washington-farewell-address",
     "title": "Washington's Farewell Address (1796)",
     "content_type": "speech", "domain": "politics",
     "source_name": "wikisource", "author": "George Washington",
     "license": "public-domain",
     "tags": ["18th-century", "american-history", "farewell"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written",
     "excerpted": True, "notes": "Partial — long original"},

    # Modern US presidential (whitehouse.gov — government-work)
    {"url": "https://www.whitehouse.gov/briefing-room/speeches-remarks/2024/03/07/remarks-of-president-joe-biden-state-of-the-union-address-as-prepared-for-delivery-2/",
     "slug": "biden-sotu-2024",
     "title": "State of the Union Address (Biden, 2024)",
     "content_type": "speech", "domain": "politics",
     "source_name": "whitehouse-gov",
     "author": "Joseph R. Biden Jr.", "license": "government-work",
     "tags": ["21st-century", "state-of-the-union"],
     "tone": "persuasive", "register": "plain", "audience": "general",
     "era": "2000-2025", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "professional", "authorship": "committee-drafted"},
    {"url": "https://bushcenter.org/about/george-w-bush/2001-inauguration-address",
     "slug": "george-w-bush-inaugural-2001",
     "title": "Inaugural Address (George W. Bush, 2001)",
     "content_type": "inaugural-address", "domain": "politics",
     "source_name": "bushcenter", "author": "George W. Bush",
     "license": "government-work",
     "tags": ["21st-century", "inaugural", "american-presidency"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "2000-2025", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "professional", "authorship": "committee-drafted"},

    # Eulogies / Sermons / Commencement
    {"url": "https://en.wikisource.org/wiki/Sermon_on_the_Mount",
     "slug": "sermon-on-the-mount-kjv",
     "title": "Sermon on the Mount (Matthew 5-7, KJV)",
     "content_type": "sermon", "domain": "religion",
     "source_name": "wikisource", "author": "Attributed to Jesus Christ",
     "license": "public-domain",
     "tags": ["new-testament", "christianity", "kjv"],
     "tone": "reverent", "register": "literary", "audience": "general",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "inform", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "anonymous"},
    {"url": "https://news.stanford.edu/2005/06/14/jobs-061505/",
     "slug": "steve-jobs-stanford-commencement-2005",
     "title": "Steve Jobs — Stanford Commencement Address (2005)",
     "content_type": "commencement-speech", "domain": "education",
     "source_name": "stanford-news", "author": "Steve Jobs",
     "license": "fair-use-excerpt",
     "tags": ["21st-century", "commencement", "silicon-valley", "memoir-speech"],
     "tone": "conversational", "register": "plain", "audience": "students",
     "era": "2000-2025", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "generalist",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # Federalist papers (additional beyond subset agent added)
    {"url": "https://en.wikisource.org/wiki/The_Federalist_Papers/No._51",
     "slug": "federalist-51",
     "title": "Federalist No. 51 (Madison)",
     "content_type": "essay", "domain": "politics",
     "source_name": "wikisource", "author": "James Madison",
     "license": "public-domain",
     "tags": ["founding-documents", "18th-century", "political-theory", "federalist"],
     "tone": "argumentative", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "persuade", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # Historical proclamation / law
    {"url": "https://en.wikisource.org/wiki/Proclamation_of_1763",
     "slug": "royal-proclamation-1763",
     "title": "Royal Proclamation of 1763",
     "content_type": "historical-document", "domain": "law",
     "source_name": "wikisource",
     "author": "King George III", "license": "public-domain",
     "tags": ["18th-century", "british-empire", "north-america"],
     "tone": "formal", "register": "bureaucratic", "audience": "experts",
     "era": "pre-1800", "perspective": "first-person", "structure": "prose",
     "purpose": "legally-bind", "expertise_required": "expert",
     "quality_disposition": "professional", "authorship": "institutional"},

    # Letters
    {"url": "https://en.wikisource.org/wiki/Letter_from_General_William_T._Sherman_to_Major_General_Henry_W._Halleck_on_his_March_to_the_Sea",
     "slug": "sherman-letter-halleck-march-to-sea",
     "title": "Letter from Sherman to Halleck on March to the Sea (1864)",
     "content_type": "letter", "domain": "history",
     "source_name": "wikisource", "author": "William T. Sherman",
     "license": "public-domain",
     "tags": ["19th-century", "american-civil-war", "military-correspondence"],
     "tone": "formal", "register": "plain", "audience": "general",
     "era": "1800-1900", "perspective": "first-person", "structure": "prose",
     "purpose": "inform", "expertise_required": "generalist",
     "quality_disposition": "professional", "authorship": "human-written"},

    # Chinese classical / Asian
    {"url": "https://en.wikisource.org/wiki/Analects/Book_II",
     "slug": "confucius-analects-book-2-legge",
     "title": "Analects — Book 2 (Legge)",
     "content_type": "philosophy-text", "domain": "philosophy",
     "source_name": "wikisource", "author": "Confucius",
     "license": "public-domain",
     "tags": ["confucianism", "chinese-philosophy", "translation"],
     "tone": "reverent", "register": "literary", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person", "structure": "prose",
     "purpose": "inform", "expertise_required": "domain-adjacent",
     "quality_disposition": "exemplary", "authorship": "human-written"},

    # Code of Hammurabi excerpt
    {"url": "https://en.wikisource.org/wiki/The_Code_of_Hammurabi_(Harper_translation)",
     "slug": "code-of-hammurabi-harper",
     "title": "Code of Hammurabi (Harper translation)",
     "content_type": "historical-document", "domain": "law",
     "source_name": "wikisource", "author": "Hammurabi",
     "license": "public-domain",
     "tags": ["ancient-law", "babylonian", "translation"],
     "tone": "formal", "register": "bureaucratic", "audience": "experts",
     "era": "pre-1800", "perspective": "third-person",
     "structure": "hierarchical-sections", "purpose": "legally-bind",
     "expertise_required": "expert", "quality_disposition": "exemplary",
     "authorship": "institutional", "excerpted": True,
     "notes": "Introduction and selected laws"},
]

if __name__ == "__main__":
    add_many(DOCS)
